### ISSUE TITLE
Redirect apex (naked) domain to www.project-helix.io

### ISSUE THREAD

**Issue by tripodsan** [adobe/project-helix.io#15]
- either with a fastly [anycast](https://docs.fastly.com/guides/basic-configuration/using-fastly-with-apex-domains) IP
- or maybe directly on Google Domains

**Comment by trieloff** [comment]
Done.

**Comment by tripodsan** [comment]
@trieloff how did you do it? I'd prefer having an explicit redirect to /index.html, then I guess the nav would work.

**Comment by trieloff** [comment]
I just changed the DNS config in Godaddy to redirect project-helix.io to www.project-helix.io. On www, Helix and Fastly take over.
