### ISSUE TITLE
Pre-requisites in getting started?

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/project-helix.io#16]
Is having git installed really a pre-requisite to get started? i haven't tried without but i am not sure it really is...

I think at this stage MacOSX is a pre-requisite though, at least for the 60s version.

**Comment by davidnuescheler** [comment]
i see, i recall that now...

it seems like an artificial or at least obscure dependency though, and it would be interest to know what needs to be done for the git server to be able to run on a directory that hasn't been inited.

i appreciate that git and github eventually become a very valid dependency later in the flow, and is probably not a big hurdle as most developers will have git installed anyway.

**Comment by kptdobe** [comment]
Prerequisites documented.
