### ISSUE TITLE
Create robot.txt and sitemap.xml

### ISSUE THREAD

**Issue by kptdobe** [adobe/project-helix.io#18]
In order for the site to be properly indexed and the search feature to work as expected with need:
- robot.txt
- sitemap.xml referencing all the pages - that's where the subdomain trick (client, pipeline) will not work anymore). 
In a first step, the sitemap will be managed manually. In a second step it could be generated out of SUMMARY.md (but what about content that does not have an entry point here...).

This would also mean that the content is properly defined.

**Comment by trieloff** [comment]
You could use `sitemapindex` to point to section-specific sitemaps: https://www.sitemaps.org/protocol.html#sitemapIndex_sitemapindex
