### ISSUE TITLE
Nav does not appear when hitting root

### ISSUE THREAD

**Issue by kptdobe** [adobe/project-helix.io#19]
Open https://www.project-helix.io/index.html
-> Nav

Open https://www.project-helix.io/
-> No nav!

**Comment by kptdobe** [comment]
Weird:

`curl -v -H "X-Debug: true" https://www.project-helix.io`

The HTML contains the ESI include tag and not the rendering: 

```
 <div class="nav">
   <!-- include https&#x3a;&#x2f;&#x2f;www.project-helix.io&#x2f;SUMMARY.summary.html-->
   <esi:include src="https://www.project-helix.io/SUMMARY.summary.html"></esi:include>
</div>
```

When running 
`curl -v -H "X-Debug: true" https://www.project-helix.io/index.html`

the ESI include is replaced by the appropriated content.

**Comment by kptdobe** [comment]
I assume this is because we enable ESI only if request extension is 'html' (helix.vcl)

```
if ( req.url.ext == "html" ) {
       set req.http.x-esi = "1";
  }
```

We need to also enable it for the "index" case (on root but also for subfolders).

**Comment by trieloff** [comment]
@kptdobe can you try setting `context.response.headers['Accept-Encoding'] = '';` in your `pre.js`. That might prototype the solution I've suggested in https://github.com/adobe/helix-cli/issues/269#issuecomment-430259262

**Comment by kptdobe** [comment]
Fixed with https://github.com/adobe/helix-cli/issues/269
