### ISSUE TITLE
Create the Fastly services for www.project-helix.io and subdomains

### ISSUE THREAD

**Issue by kptdobe** [adobe/project-helix.io#2]
Once the domain name has been registered (see https://github.com/adobe/project-helix.io/issues/1),
we need to configure the Fastly service.
- [x] Create the services in Fastly following the documentation https://github.com/adobe/project-helix/blob/master/getting-started.md#onboarding-a-domain
  - [x] Create a service for project-helix.io
  - [x] Create a service or strains for `www`, `hypermedia-pipeline`, `helix-cli` subdomains
- [x] Update the documentation if needed

**Comment by kptdobe** [comment]
The documentation was correct and up-to-date.

Created one fastly services and multiple strains.

Creating and managing the strains is pretty straight forward, the deployment is less: many cache issues. Hitting a first time https://client.project-helix.io/README.html caches the strain in a cookie thus  changing it later was hard to get it up-to-date (new incognito window). Also the browser caches the content pretty strongly: still not up-to-date in my current normal Chrome window (new incognito window again).

Biggest pain point: the navigation. The links must be absolute because when switching from one content repo to another, the links must be absolute to their repo. Invented some code (see https://github.com/adobe/project-helix.io/blob/master/src/summary_html.pre.js#L39-L43 and nav content here https://github.com/adobe/project-helix.io/edit/master/SUMMARY.md) which is fine for now but probably not the best final approach.

**Comment by tripodsan** [comment]
the problem is, that we should not use different domains for different strains. this is also a problem for cache invalidation. I always thought that:

1 helix-config.yaml -> 1 domain -> 1 fastly service

the stains within 1 config cannot have a different domain. only different domain roots.
if you need the same code but different content, you need to create a new configuration only git repo.

@trieloff WDYT?

**Comment by kptdobe** [comment]
I agree the solution is not optimal but at least generated the less effort and the less to maintain: (3 strains in 1 repo + 1 service) is way easier to maintain than (1 strain in 3 repo + 3 services). Especially if we need to introduce "configuration only" git repo.

Could you describe the cache invalidation issues we may have with the current setup ? 

I think the whole strain concept have to be re-thought or at least to be hidden for such simple use cases.

I can change the setup to what you propose and see if things are easier to handle.

**Comment by tripodsan** [comment]
I wonder, why you want to create 3 websites (domains) with the same config repo? IMO this is not a real life use case. I would assume, the 2 other  parts are sub-directories of the www one.

> Could you describe the cache invalidation issues we may have with the current setup ?

hmmm... probably none, in the long run :-) we anyways need to lookup the configuration from the content repos, and then figure out the service ids and then purge the respective domains....or surrogate keys. currenty, we can only purgeAll an entire service.

but I still think, that 1 helix-config.yaml (including its strains) should only map to 1 service and only handle 1 domain. we could support multi-config repositories. eg:

```
/helix.io
  /config
    /www.project.helix.io
      /helix-config.yaml
    /client.project.helix.io
      /helix-config.yaml
    /docs.project.helix.io
      /helix-config.yaml
```

**Comment by kptdobe** [comment]
> I wonder, why you want to create 3 websites (domains) with the same config repo? IMO this is not a real life use case. I would assume, the 2 other parts are sub-directories of the www one.

I am only trying to use the tool I am provided with for now with the simplest approach. I want to have one single place where I manage the whole setup. Here are my "customer" requirements:
- My site is `project-helix.io`
- The root, the nav, the main content and the code is stored in the `project-helix.io`
- I only have some few content coming from external content repos, like client (helix-cli) and pipeline (hypermedia-pipeline repo)
- This external content should be rendered using the same code
- The nav is generic to all repos and the same everywhere

I think having multiple content repos for one single site is a common use case (question asked by Kaneka on day one of the last hackathon). I am fine if 1 helix-config.yaml = 1 service, thus maybe this is not what I need to achieve my simple goal. I might need something the other way around and I should be able to define for my `project-helix.io` project something like:
- www = (code in project-helix.io repo + content in project-helix.io repo)
- client = (code in project-helix.io repo + content in helix-cli repo)
...

If I can describe this somehow and if there is no technical reason why there would be multiple Fastly services, then maybe we need to revisit the strain concept... I am not sure someone will be able to understand anyway that you can set a cookie or a header to get a different revision of your site.

Anyway, I am creating new services now.

**Comment by tripodsan** [comment]
> Anyway, I am creating new services now.

no, I think this would be the wrong approach.
I think the strains should be able to do something like:

```
- strain:
    name: default
    url: www.project.helix.io
    content:
      repo: project-helix.io
      ref: master
      owner: adobe
- strain:
    name: client
    url: www.project.helix.io/client
    content:
      repo: helix-cli
      ref: master
      owner: adobe
- strain:
    name: pipeline
    url: www.project.helix.io/pipeline
    content:
      repo: hypermedia-pipeline
      ref: master
      owner: adobe
```

**Comment by kptdobe** [comment]
Relates to https://github.com/adobe/helix-cli/issues/118

**Comment by kptdobe** [comment]
Fixed with https://github.com/adobe/project-helix.io/issues/36
