### ISSUE TITLE
host hlx install script on project-helix.io

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/project-helix.io#21]
to support `hlx` installation via curl:

```bash
curl -sL http://www.project-helix.io/cli.sh | sh
```

**Comment by stefan-guggisberg** [comment]
i've added `src/static/cli.sh` and i can request it locally (via `hlx up`). however `http://www.project-helix.io/cli.sh` returns a `404`.

@kptdobe i guess the old-style static handling is still deployed and needs to be updated. how can i do that? `hlx publish`?

**Comment by tripodsan** [comment]
I fixed it:

```
curl https://www.project-helix.io/cli.sh
```
