### ISSUE TITLE
code references in config file are wrong

### ISSUE THREAD

**Issue by trieloff** [adobe/project-helix.io#28]
https://github.com/adobe/project-helix.io/blob/de8d9e0f9b5dae1faef692d4a2eaa0e93c72cc57/helix-config.yaml#L25

This should end with `master--` not `master--html`. @tripodsan do you remember why you've made that change?

**Comment by tripodsan** [comment]
hmmm, it didn't work w/o the `html`. in the end, I got it to deploy and publish...

**Comment by kptdobe** [comment]
Removed the `html` and works. See https://github.com/adobe/project-helix.io/commit/abb33e6ab2ba1b66393050dbad2703c38fd64857
