### ISSUE TITLE
Content assets are missing

### ISSUE THREAD

**Issue by kptdobe** [adobe/project-helix.io#29]
Run `hlx up`
-> all requests `/assets/*.png` returns 404.

hlx version: v0.10.10

**Comment by tripodsan** [comment]
> why is now the webroot appended to "content" assets ??

don't confuse the local development case with the remote case :-)

**Comment by tripodsan** [comment]
this broke it: https://github.com/adobe/helix-simulator/commit/712aa44fcb64ab989ce544652c754e278f138f8a#diff-2b4ca49d4bb0a774c4d4c1672d7aa781L76

**Comment by kptdobe** [comment]
Fixed with https://github.com/adobe/helix-simulator/issues/116 and corresponding smoke tests added.
