### ISSUE TITLE
Cannot install helix on Windows 10

### ISSUE THREAD

**Issue by rstratulat** [adobe/project-helix.io#42]
λ curl -sL https://www.project-helix.io/cli.sh | sh

downloading hlx installer v0.13.10 ...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   605    0   605    0     0    605      0 --:--:-- --:--:-- --:--:--   860
100 36.2M  100 36.2M    0     0  7414k      0  0:00:05  0:00:05 --:--:-- 8659k

running hlx installer v0.13.10 ...

Verifying archive integrity...  100%   All good.
Uncompressing SFX installer for hlx  100%

cp: cannot create regular file '/usr/local/bin/hlx': No such file or directory
failed to install hlx, aborting

**Comment by kptdobe** [comment]
@rstratulat Thanks for reporting!

While this makes total sense to have created the issue in this repo, this is related to the cli thus moving to https://github.com/adobe/helix-cli issue. 

/move adobe/helix-cli
