### ISSUE TITLE
Debug instruction in documentation on https://www.project-helix.io/ website

### ISSUE THREAD

**Issue by wielmic** [adobe/project-helix.io#47]
This is a minor thing but might be worth to mention. When i try to debug helix demo project on windows using vscode, the instruction doesn't work. I need to add remote server or debug the process manually.

**Comment by trieloff** [comment]
Can you describe the detailed steps you are taking, so that we can add it to the docs?

**Comment by wielmic** [comment]
Sure
Click Debug > add configuration > attach to process. Then click run button and select helix process from the list of active processes. The one with path to the helix-cli.

**Comment by rofe** [comment]
Site archived in favor of https://www.hlx.live
