### ISSUE TITLE
Documentation: clarification regarding dynamically rendered components

### ISSUE THREAD

**Issue by wielmic** [adobe/project-helix.io#49]
I couldn't find in the documentation any information how to create a page with dynamic elements. For example if it is possible or how to create dynamically computed navigation.
It can be created using github api in the rendering script but does helix provide any support for this? Github api has limits and they might be low for anonymous user, this could be resolved by account support. 

It would be great to have some concept outlined in Documentation. If it is not recommended to build such structures with helix it is good to mention it there also.

**Comment by rofe** [comment]
Site archived in favor of https://www.hlx.live
