### ISSUE TITLE
Invalid last modified date

### ISSUE THREAD

**Issue by rofe** [adobe/project-helix.io#59]
The header showing who modified the content last and when shows "invalid date"

e.g. https://www.project-helix.io/doc/getting-started/how-helix-works.html

**Comment by rofe** [comment]
Moment.js is choking on the XSS encoded raw date value.

**Comment by tripodsan** [comment]
cause by https://github.com/adobe/htlengine/issues/84

**Comment by tripodsan** [comment]
should be fixed with https://github.com/adobe/helix-cli/releases/tag/v4.9.13

**Comment by rofe** [comment]
Confirmed fixed
