### ISSUE TITLE
/pipeline/README.html doesn't work anymore

### ISSUE THREAD

**Issue by tripodsan** [adobe/project-helix.io#69]
maybe we need to rewrite the `helix-config.yaml` to use conditions?

@dominique-pfister @trieloff  ?

**Comment by dominique-pfister** [comment]
Surely a good idea to good conditions, but can you add some context? What is the relation to `/pipeline/README.html` not working anymore?

**Comment by tripodsan** [comment]
the _pipeline_ strain is/was selected with an url:

https://github.com/adobe/project-helix.io/blob/e79e968e1b34b4d151731015880a9b4a71efe7a5/helix-config.yaml#L29-L33

I suspect this no longer works with the recent version of simluator and VCL.

**Comment by dominique-pfister** [comment]
Hmm, but the fallback to using `url` is still in place.

**Comment by tripodsan** [comment]
it works in the local development, but not deployed to fastly:

```
x-url: /pipeline/README.html
x-backend-url: /api/v1/web/helix-pages/helix-services/dispatch@v3?static.owner=adobe&static.repo=project-helix.io&static.ref=master&static.root=/htdocs&content.owner=adobe&content.repo=project-helix.io&content.ref=master&content.root=&content.package=c14f43cc8041cbcb248b40095920799b7773c63f&content.index=index.html&path=/pipeline/README.html&strain=default&rootPath=&params=
```

**Comment by tripodsan** [comment]
looks a bit empty:

![image](https://user-images.githubusercontent.com/917628/77492324-a23e8980-6e83-11ea-865e-d0b01403bf39.png)

the previous version was:

![image](https://user-images.githubusercontent.com/917628/77492359-bb473a80-6e83-11ea-9a27-8c57847e4095.png)

**Comment by tripodsan** [comment]
see failing test in https://github.com/adobe/helix-publish/pull/373
