### ISSUE TITLE
[project-helix.io] Clicking on anatomy of the pipeline results in 403 forbidden

### ISSUE THREAD

**Issue by iulianbarbu** [adobe/project-helix.io#83]
### Expected Behaviour
I expect to land on a page with some relevant information when I click on:
![image](https://user-images.githubusercontent.com/14218860/117620871-98f0a900-b179-11eb-9c94-365523062adc.png)

### Actual Behaviour
When clicking on the above list item I get a 403 forbidden page:
![image](https://user-images.githubusercontent.com/14218860/117621352-32b85600-b17a-11eb-9760-96a0c180cc6d.png)

### Reproduce Scenario (including but not limited to):
Open Google Chrome and go to: https://www.project-helix.io/pipeline/README.html.

#### Platform and Version
Google Chrome Version 90.0.4430.85 (Official Build) (x86_64) - MacOS BigSur

**Comment by rofe** [comment]
Site archived in favor of https://www.hlx.live
